name: Check format and lint
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Check format and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run prettier:check
      - name: Lint
        run: npm run lint
